kind: pipeline
type: ssh
name: 同步321CQU公共仓库

server:
  host:
    from_secret: ssh_host
  user: root
  ssh_key:
    from_secret: ssh_key

platform:
  os: linux
  arсh: amd64

clone:
  disable: true

steps:
  - name: clone
    environment:
      ENV_FILE_PATH: ./.env
    commands:
      - git config --global http.proxy http://127.0.0.1:7890
      - git config --global https.proxy http://127.0.0.1:7890
      - git clone https://github.com/321CQU/Public_Repository.git
      - cd ./Public_Repository
      - git checkout main
      - source $ENV_FILE_PATH
      - cp -a -r -f ./micro_services_protobuf/ $${_321CQU_PUBLIC_REPOSITORY_PATH}/micro_services_protobuf/
      - cp -a -r -f ./python_package/_321CQU/ $${_321CQU_PUBLIC_REPOSITORY_PATH}/python_package/
      - cp -a -r -f ./python_package/micro_services_protobuf/ $${_321CQU_PUBLIC_REPOSITORY_PATH}/python_package/
      - cp -a -r -f ./proto_build/python/micro_services_protobuf $${_321CQU_PUBLIC_REPOSITORY_PATH}/python_package/
      - cp -a -r -f ./docker-compose.yml $${_321CQU_PUBLIC_REPOSITORY_PATH}/
      - cp -a -r -f $ENV_FILE_PATH $${_321CQU_PUBLIC_REPOSITORY_PATH}/

trigger:
  branch:
    - main
  event:
    - push
    - merge

---
kind: pipeline
type: docker
name: 通知

clone:
  disable: true

steps:
  - name: 钉钉通知
    image: lddsb/drone-dingtalk-message
    settings:
      token:
        from_secret: dingtalk_token
      secret:
        from_secret: dingtalk_sign
      type: markdown
      message_color: true
      message_pic: true
      sha_link: true

trigger:
  status:
    - success
    - failure

depends_on:
  - 同步321CQU公共仓库
