kind: pipeline
type: ssh
name: 同步321CQU公共仓库

server:
  host:
    from_secret: ssh_host
  user: root
  ssh_key:
    from_secret: ssh_key

platform:
  os: linux
  arсh: amd64

clone:
  disable: true

steps:
- name: clone
  commands:
    - git config --global http.proxy http://127.0.0.1:7890
    - git config --global https.proxy http://127.0.0.1:7890
    - git clone https://github.com/ZhuLegend/321CQU_Public_Repository.git
    - git checkout main
    - cp -a -r -f ./321CQU_Public_Repository/micro_services_protobuf/ /www/services/_321CQU_package/micro_services_protobuf/
    - cp -a -r -f ./321CQU_Public_Repository/python_package/_321CQU/ /www/services/_321CQU_package/python_package/
    - cp -a -r -f ./321CQU_Public_Repository/python_package/micro_services_protobuf/ /www/services/_321CQU_package/python_package/

trigger:
  branch:
  - main
  event:
  - push
  - merge

---
kind: pipeline
type: docker
name: 通知

clone:
  disable: true

steps:
  - name: 钉钉通知
    image: lddsb/drone-dingtalk-message
    settings:
      token:
        from_secret: dingtalk_token
      secret:
        from_secret: dingtalk_sign
      type: markdown
      message_color: true
      message_pic: true
      sha_link: true

depends_on:
  - 同步321CQU公共仓库
