version: '3'
services:
  control-center:
    container_name: 321cqu-control-center
    image: ${CONTROL_CENTER_IMAGE}
    expose:
      - ${CONTROL_CENTER_EXPOSE_PORT}
    restart: always
    volumes:
      - ${CONTROL_CENTER_HOME_DIR}/config:/etc/ControlCenter:ro
    networks:
      - persist

  api-gateway:
    container_name: 321cqu-api-gateway
    image: ${API_GATEWAY_IMAGE}
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - ${API_GATEWAY_HOME_DIR}/logs:/src/logs
      - ${API_GATEWAY_HOME_DIR}/config.cfg:/src/utils/config.cfg
      - ${_321CQU_PUBLIC_REPOSITORY_PATH}/python_package:/_321CQU_package
    environment:
      PYTHONPATH: /_321CQU_package
    networks:
      - persist

  edu-admin-center:
    container_name: 321cqu-edu-admin-center
    image: ${EDU_ADMIN_CENTER_IMAGE}
    expose:
      - ${EDU_ADMIN_CENTER_EXPOSE_PORT}
    restart: always
    volumes:
      - ${EDU_ADMIN_CENTER_HOME_DIR}/config:/src/utils/config
      - ${_321CQU_PUBLIC_REPOSITORY_PATH}/python_package:/_321CQU_package
    environment:
      PYTHONPATH: /_321CQU_package
    networks:
      - persist

  mycqu-service:
    container_name: 321cqu-mycqu-service
    image: ${MYCQU_SERVICE_IMAGE}
    expose:
      - ${MYCQU_SERVICE_EXPOSE_PORT}
    restart: always
    volumes:
      - ${MYCQU_SERVICE_HOME_DIR}/config:/src/utils/config
      - ${_321CQU_PUBLIC_REPOSITORY_PATH}/python_package:/_321CQU_package
    environment:
      PYTHONPATH: /_321CQU_package
      PROXY_PASSWORD: ${PROXY_PASSWORD}
      PROXY_USERNAME: ${PROXY_USERNAME}
      PROXY_SECRET_ID: ${PROXY_SECRET_ID}
      PROXY_SIGNATURE: ${PROXY_SIGNATURE}
    networks:
      - persist

networks:
  persist:
    external:
      name: 321cqu