# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: micro_services_protobuf/course_score_query/model.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from micro_services_protobuf.mycqu_service import mycqu_model_pb2 as micro__services__protobuf_dot_mycqu__service_dot_mycqu__model__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n6micro_services_protobuf/course_score_query/model.proto\x12\x12\x63ourse_score_query\x1a\x37micro_services_protobuf/mycqu_service/mycqu_model.proto\"Z\n\x17\x46indCourseByNameRequest\x12\x15\n\x0b\x63ourse_name\x18\x01 \x01(\tH\x00\x12\x16\n\x0cteacher_name\x18\x02 \x01(\tH\x00\x42\x10\n\x0esearch_keyword\"B\n\x18\x46indCourseByNameResponse\x12&\n\x07\x63ourses\x18\x01 \x03(\x0b\x32\x15.mycqu_service.Course\"5\n\x1e\x46\x65tchLayeredScoreDetailRequest\x12\x13\n\x0b\x63ourse_code\x18\x01 \x01(\t\"\xf0\x02\n\x12LayeredScoreDetail\x12\x14\n\x0cteacher_name\x18\x01 \x01(\t\x12N\n\x07\x64\x65tails\x18\x02 \x03(\x0b\x32=.course_score_query.LayeredScoreDetail.LayeredTermScoreDetail\x1a\xf3\x01\n\x16LayeredTermScoreDetail\x12\'\n\x04term\x18\x01 \x01(\x0b\x32\x19.mycqu_service.CquSession\x12\x14\n\x0cis_hierarchy\x18\x02 \x01(\x08\x12\x0b\n\x03max\x18\x03 \x01(\x02\x12\x0b\n\x03min\x18\x04 \x01(\x02\x12\x0f\n\x07\x61verage\x18\x05 \x01(\x02\x12\x0b\n\x03num\x18\x06 \x01(\x05\x12\x12\n\nlevel1_num\x18\x07 \x01(\x05\x12\x12\n\nlevel2_num\x18\x08 \x01(\x05\x12\x12\n\nlevel3_num\x18\t \x01(\x05\x12\x12\n\nlevel4_num\x18\n \x01(\x05\x12\x12\n\nlevel5_num\x18\x0b \x01(\x05\"\x8a\x01\n\x1f\x46\x65tchLayeredScoreDetailResponse\x12\x13\n\x0b\x63ourse_name\x18\x01 \x01(\t\x12\x13\n\x0b\x63ourse_code\x18\x02 \x01(\t\x12=\n\rscore_details\x18\x03 \x03(\x0b\x32&.course_score_query.LayeredScoreDetailb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'micro_services_protobuf.course_score_query.model_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FINDCOURSEBYNAMEREQUEST._serialized_start=135
  _FINDCOURSEBYNAMEREQUEST._serialized_end=225
  _FINDCOURSEBYNAMERESPONSE._serialized_start=227
  _FINDCOURSEBYNAMERESPONSE._serialized_end=293
  _FETCHLAYEREDSCOREDETAILREQUEST._serialized_start=295
  _FETCHLAYEREDSCOREDETAILREQUEST._serialized_end=348
  _LAYEREDSCOREDETAIL._serialized_start=351
  _LAYEREDSCOREDETAIL._serialized_end=719
  _LAYEREDSCOREDETAIL_LAYEREDTERMSCOREDETAIL._serialized_start=476
  _LAYEREDSCOREDETAIL_LAYEREDTERMSCOREDETAIL._serialized_end=719
  _FETCHLAYEREDSCOREDETAILRESPONSE._serialized_start=722
  _FETCHLAYEREDSCOREDETAILRESPONSE._serialized_end=860
# @@protoc_insertion_point(module_scope)
