# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: micro_services_protobuf/common.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$micro_services_protobuf/common.proto\x12\x06\x63ommon\"\x1e\n\x0f\x44\x65\x66\x61ultResponse\x12\x0b\n\x03msg\x18\x01 \x01(\t\"\x15\n\x06UserId\x12\x0b\n\x03uid\x18\x01 \x01(\x0c\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'micro_services_protobuf.common_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DEFAULTRESPONSE']._serialized_start=48
  _globals['_DEFAULTRESPONSE']._serialized_end=78
  _globals['_USERID']._serialized_start=80
  _globals['_USERID']._serialized_end=101
# @@protoc_insertion_point(module_scope)
