# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: micro_services_protobuf/notification_center/apns.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n6micro_services_protobuf/notification_center/apns.proto\x12\x13notification_center\".\n\x12SetUserApnsRequest\x12\x0b\n\x03uid\x18\x01 \x01(\x0c\x12\x0b\n\x03\x61pn\x18\x02 \x01(\x0c\"\xe8\x02\n\x1bSendApnsNotificationRequest\x12\x0b\n\x03\x61pn\x18\x01 \x01(\x0c\x12X\n\x0cnotification\x18\x02 \x01(\x0b\x32\x42.notification_center.SendApnsNotificationRequest.AppleNotification\x1a\xe1\x01\n\x11\x41ppleNotification\x12\\\n\x05\x61lert\x18\x01 \x01(\x0b\x32M.notification_center.SendApnsNotificationRequest.AppleNotification.AppleAlert\x12\r\n\x05\x62\x61\x64ge\x18\x02 \x01(\x05\x12\x10\n\x08\x63\x61tegory\x18\x03 \x01(\t\x1aM\n\nAppleAlert\x12\r\n\x05title\x18\x01 \x01(\t\x12\x15\n\x08subtitle\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x0c\n\x04\x62ody\x18\x03 \x01(\tB\x0b\n\t_subtitleb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'micro_services_protobuf.notification_center.apns_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SETUSERAPNSREQUEST._serialized_start=79
  _SETUSERAPNSREQUEST._serialized_end=125
  _SENDAPNSNOTIFICATIONREQUEST._serialized_start=128
  _SENDAPNSNOTIFICATIONREQUEST._serialized_end=488
  _SENDAPNSNOTIFICATIONREQUEST_APPLENOTIFICATION._serialized_start=263
  _SENDAPNSNOTIFICATIONREQUEST_APPLENOTIFICATION._serialized_end=488
  _SENDAPNSNOTIFICATIONREQUEST_APPLENOTIFICATION_APPLEALERT._serialized_start=411
  _SENDAPNSNOTIFICATIONREQUEST_APPLENOTIFICATION_APPLEALERT._serialized_end=488
# @@protoc_insertion_point(module_scope)
