global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: api-gateway
    metrics_path: /metrics
    bearer_token_file: /etc/prometheus/token
    static_configs:
      - targets:
          - api-gateway:8000

  - job_name: mycqu-service
    metrics_path: /metrics
    static_configs:
      - targets:
          - mycqu-service:93211

  - job_name: edu-admin-center
    metrics_path: /metrics
    static_configs:
      - targets:
          - edu-admin-center:93212
