# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: micro_services_protobuf/notification_center/service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from micro_services_protobuf import common_pb2 as micro__services__protobuf_dot_common__pb2
from micro_services_protobuf.notification_center import apns_pb2 as micro__services__protobuf_dot_notification__center_dot_apns__pb2
from micro_services_protobuf.notification_center import event_pb2 as micro__services__protobuf_dot_notification__center_dot_event__pb2
from micro_services_protobuf.notification_center import wechat_pb2 as micro__services__protobuf_dot_notification__center_dot_wechat__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n9micro_services_protobuf/notification_center/service.proto\x12\x13notification_center\x1a$micro_services_protobuf/common.proto\x1a\x36micro_services_protobuf/notification_center/apns.proto\x1a\x37micro_services_protobuf/notification_center/event.proto\x1a\x38micro_services_protobuf/notification_center/wechat.proto2\xbc\x01\n\x04\x41pns\x12O\n\x0bSetUserApns\x12\'.notification_center.SetUserApnsRequest\x1a\x17.common.DefaultResponse\x12\x63\n\x16SendNotificationToUser\x12\x30.notification_center.SendApnsNotificationRequest\x1a\x17.common.DefaultResponse2\xc6\x01\n\x06Wechat\x12S\n\rSetUserOpenId\x12).notification_center.SetUserOpenIdRequest\x1a\x17.common.DefaultResponse\x12g\n\x17HandleWechatServerEvent\x12\x33.notification_center.HandleWechatServerEventRequest\x1a\x17.common.DefaultResponse2\xc8\x01\n\x0cNotification\x12\x61\n\x14UpdateEventSubscribe\x12\x30.notification_center.UpdateEventSubscribeRequest\x1a\x17.common.DefaultResponse\x12U\n\x12\x46\x65tchSubscribeInfo\x12\x0e.common.UserId\x1a/.notification_center.FetchSubscribeInfoResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'micro_services_protobuf.notification_center.service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_APNS']._serialized_start=292
  _globals['_APNS']._serialized_end=480
  _globals['_WECHAT']._serialized_start=483
  _globals['_WECHAT']._serialized_end=681
  _globals['_NOTIFICATION']._serialized_start=684
  _globals['_NOTIFICATION']._serialized_end=884
# @@protoc_insertion_point(module_scope)
