# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from micro_services_protobuf.edu_admin_center import eac_models_pb2 as micro__services__protobuf_dot_edu__admin__center_dot_eac__models__pb2
from micro_services_protobuf.mycqu_service import mycqu_model_pb2 as micro__services__protobuf_dot_mycqu__service_dot_mycqu__model__pb2
from micro_services_protobuf.mycqu_service import mycqu_request_response_pb2 as micro__services__protobuf_dot_mycqu__service_dot_mycqu__request__response__pb2


class EduAdminCenterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ValidateAuth = channel.unary_unary(
                '/edu_admin_center.EduAdminCenter/ValidateAuth',
                request_serializer=micro__services__protobuf_dot_mycqu__service_dot_mycqu__request__response__pb2.BaseLoginInfo.SerializeToString,
                response_deserializer=micro__services__protobuf_dot_edu__admin__center_dot_eac__models__pb2.ValidateAuthResponse.FromString,
                )
        self.FetchEnrollCourseInfo = channel.unary_unary(
                '/edu_admin_center.EduAdminCenter/FetchEnrollCourseInfo',
                request_serializer=micro__services__protobuf_dot_mycqu__service_dot_mycqu__request__response__pb2.FetchEnrollCourseInfoRequest.SerializeToString,
                response_deserializer=micro__services__protobuf_dot_mycqu__service_dot_mycqu__request__response__pb2.FetchEnrollCourseInfoResponse.FromString,
                )
        self.FetchEnrollCourseItem = channel.unary_unary(
                '/edu_admin_center.EduAdminCenter/FetchEnrollCourseItem',
                request_serializer=micro__services__protobuf_dot_mycqu__service_dot_mycqu__request__response__pb2.FetchEnrollCourseItemRequest.SerializeToString,
                response_deserializer=micro__services__protobuf_dot_mycqu__service_dot_mycqu__request__response__pb2.FetchEnrollCourseItemResponse.FromString,
                )
        self.FetchExam = channel.unary_unary(
                '/edu_admin_center.EduAdminCenter/FetchExam',
                request_serializer=micro__services__protobuf_dot_mycqu__service_dot_mycqu__request__response__pb2.FetchExamRequest.SerializeToString,
                response_deserializer=micro__services__protobuf_dot_mycqu__service_dot_mycqu__request__response__pb2.FetchExamResponse.FromString,
                )
        self.FetchCourseTimetable = channel.unary_unary(
                '/edu_admin_center.EduAdminCenter/FetchCourseTimetable',
                request_serializer=micro__services__protobuf_dot_edu__admin__center_dot_eac__models__pb2.FetchCourseTimetableRequest.SerializeToString,
                response_deserializer=micro__services__protobuf_dot_edu__admin__center_dot_eac__models__pb2.FetchCourseTimetableResponse.FromString,
                )
        self.FetchScore = channel.unary_unary(
                '/edu_admin_center.EduAdminCenter/FetchScore',
                request_serializer=micro__services__protobuf_dot_edu__admin__center_dot_eac__models__pb2.FetchScoreRequest.SerializeToString,
                response_deserializer=micro__services__protobuf_dot_mycqu__service_dot_mycqu__request__response__pb2.FetchScoreResponse.FromString,
                )
        self.FetchGpaRanking = channel.unary_unary(
                '/edu_admin_center.EduAdminCenter/FetchGpaRanking',
                request_serializer=micro__services__protobuf_dot_mycqu__service_dot_mycqu__request__response__pb2.BaseLoginInfo.SerializeToString,
                response_deserializer=micro__services__protobuf_dot_mycqu__service_dot_mycqu__model__pb2.GpaRanking.FromString,
                )


class EduAdminCenterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ValidateAuth(self, request, context):
        """获取用户信息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchEnrollCourseInfo(self, request, context):
        """获取可选课程信息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchEnrollCourseItem(self, request, context):
        """获取可选具体课程信息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchExam(self, request, context):
        """获取考试信息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchCourseTimetable(self, request, context):
        """获取课表
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchScore(self, request, context):
        """获取成绩信息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchGpaRanking(self, request, context):
        """获取绩点排名信息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EduAdminCenterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ValidateAuth': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateAuth,
                    request_deserializer=micro__services__protobuf_dot_mycqu__service_dot_mycqu__request__response__pb2.BaseLoginInfo.FromString,
                    response_serializer=micro__services__protobuf_dot_edu__admin__center_dot_eac__models__pb2.ValidateAuthResponse.SerializeToString,
            ),
            'FetchEnrollCourseInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchEnrollCourseInfo,
                    request_deserializer=micro__services__protobuf_dot_mycqu__service_dot_mycqu__request__response__pb2.FetchEnrollCourseInfoRequest.FromString,
                    response_serializer=micro__services__protobuf_dot_mycqu__service_dot_mycqu__request__response__pb2.FetchEnrollCourseInfoResponse.SerializeToString,
            ),
            'FetchEnrollCourseItem': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchEnrollCourseItem,
                    request_deserializer=micro__services__protobuf_dot_mycqu__service_dot_mycqu__request__response__pb2.FetchEnrollCourseItemRequest.FromString,
                    response_serializer=micro__services__protobuf_dot_mycqu__service_dot_mycqu__request__response__pb2.FetchEnrollCourseItemResponse.SerializeToString,
            ),
            'FetchExam': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchExam,
                    request_deserializer=micro__services__protobuf_dot_mycqu__service_dot_mycqu__request__response__pb2.FetchExamRequest.FromString,
                    response_serializer=micro__services__protobuf_dot_mycqu__service_dot_mycqu__request__response__pb2.FetchExamResponse.SerializeToString,
            ),
            'FetchCourseTimetable': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchCourseTimetable,
                    request_deserializer=micro__services__protobuf_dot_edu__admin__center_dot_eac__models__pb2.FetchCourseTimetableRequest.FromString,
                    response_serializer=micro__services__protobuf_dot_edu__admin__center_dot_eac__models__pb2.FetchCourseTimetableResponse.SerializeToString,
            ),
            'FetchScore': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchScore,
                    request_deserializer=micro__services__protobuf_dot_edu__admin__center_dot_eac__models__pb2.FetchScoreRequest.FromString,
                    response_serializer=micro__services__protobuf_dot_mycqu__service_dot_mycqu__request__response__pb2.FetchScoreResponse.SerializeToString,
            ),
            'FetchGpaRanking': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchGpaRanking,
                    request_deserializer=micro__services__protobuf_dot_mycqu__service_dot_mycqu__request__response__pb2.BaseLoginInfo.FromString,
                    response_serializer=micro__services__protobuf_dot_mycqu__service_dot_mycqu__model__pb2.GpaRanking.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'edu_admin_center.EduAdminCenter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class EduAdminCenter(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ValidateAuth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/edu_admin_center.EduAdminCenter/ValidateAuth',
            micro__services__protobuf_dot_mycqu__service_dot_mycqu__request__response__pb2.BaseLoginInfo.SerializeToString,
            micro__services__protobuf_dot_edu__admin__center_dot_eac__models__pb2.ValidateAuthResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FetchEnrollCourseInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/edu_admin_center.EduAdminCenter/FetchEnrollCourseInfo',
            micro__services__protobuf_dot_mycqu__service_dot_mycqu__request__response__pb2.FetchEnrollCourseInfoRequest.SerializeToString,
            micro__services__protobuf_dot_mycqu__service_dot_mycqu__request__response__pb2.FetchEnrollCourseInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FetchEnrollCourseItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/edu_admin_center.EduAdminCenter/FetchEnrollCourseItem',
            micro__services__protobuf_dot_mycqu__service_dot_mycqu__request__response__pb2.FetchEnrollCourseItemRequest.SerializeToString,
            micro__services__protobuf_dot_mycqu__service_dot_mycqu__request__response__pb2.FetchEnrollCourseItemResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FetchExam(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/edu_admin_center.EduAdminCenter/FetchExam',
            micro__services__protobuf_dot_mycqu__service_dot_mycqu__request__response__pb2.FetchExamRequest.SerializeToString,
            micro__services__protobuf_dot_mycqu__service_dot_mycqu__request__response__pb2.FetchExamResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FetchCourseTimetable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/edu_admin_center.EduAdminCenter/FetchCourseTimetable',
            micro__services__protobuf_dot_edu__admin__center_dot_eac__models__pb2.FetchCourseTimetableRequest.SerializeToString,
            micro__services__protobuf_dot_edu__admin__center_dot_eac__models__pb2.FetchCourseTimetableResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FetchScore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/edu_admin_center.EduAdminCenter/FetchScore',
            micro__services__protobuf_dot_edu__admin__center_dot_eac__models__pb2.FetchScoreRequest.SerializeToString,
            micro__services__protobuf_dot_mycqu__service_dot_mycqu__request__response__pb2.FetchScoreResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FetchGpaRanking(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/edu_admin_center.EduAdminCenter/FetchGpaRanking',
            micro__services__protobuf_dot_mycqu__service_dot_mycqu__request__response__pb2.BaseLoginInfo.SerializeToString,
            micro__services__protobuf_dot_mycqu__service_dot_mycqu__model__pb2.GpaRanking.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
