# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: micro_services_protobuf/edu_admin_center/eac_models.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from micro_services_protobuf.mycqu_service import mycqu_model_pb2 as micro__services__protobuf_dot_mycqu__service_dot_mycqu__model__pb2
from micro_services_protobuf.mycqu_service import mycqu_request_response_pb2 as micro__services__protobuf_dot_mycqu__service_dot_mycqu__request__response__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n9micro_services_protobuf/edu_admin_center/eac_models.proto\x12\x10\x65\x64u_admin_center\x1a\x37micro_services_protobuf/mycqu_service/mycqu_model.proto\x1a\x42micro_services_protobuf/mycqu_service/mycqu_request_response.proto\"L\n\x14ValidateAuthResponse\x12\x0b\n\x03sid\x18\x01 \x01(\t\x12\x0c\n\x04\x61uth\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0b\n\x03uid\x18\x04 \x01(\x0c\"m\n\x1b\x46\x65tchCourseTimetableRequest\x12\x30\n\nlogin_info\x18\x01 \x01(\x0b\x32\x1c.mycqu_service.BaseLoginInfo\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\x12\x0e\n\x06offset\x18\x03 \x01(\x05\"\x95\x01\n\x1c\x46\x65tchCourseTimetableResponse\x12\x39\n\x11\x63ourse_timetables\x18\x01 \x03(\x0b\x32\x1e.mycqu_service.CourseTimetable\x12\x12\n\nstart_date\x18\x02 \x01(\t\x12\x10\n\x08\x65nd_date\x18\x03 \x01(\t\x12\x14\n\x0csession_name\x18\x04 \x01(\t\"i\n\x11\x46\x65tchScoreRequest\x12\x35\n\x0f\x62\x61se_login_info\x18\x01 \x01(\x0b\x32\x1c.mycqu_service.BaseLoginInfo\x12\x0b\n\x03sid\x18\x02 \x01(\t\x12\x10\n\x08is_minor\x18\x03 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'micro_services_protobuf.edu_admin_center.eac_models_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_VALIDATEAUTHRESPONSE']._serialized_start=204
  _globals['_VALIDATEAUTHRESPONSE']._serialized_end=280
  _globals['_FETCHCOURSETIMETABLEREQUEST']._serialized_start=282
  _globals['_FETCHCOURSETIMETABLEREQUEST']._serialized_end=391
  _globals['_FETCHCOURSETIMETABLERESPONSE']._serialized_start=394
  _globals['_FETCHCOURSETIMETABLERESPONSE']._serialized_end=543
  _globals['_FETCHSCOREREQUEST']._serialized_start=545
  _globals['_FETCHSCOREREQUEST']._serialized_end=650
# @@protoc_insertion_point(module_scope)
