# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from micro_services_protobuf.control_center import control_center_models_pb2 as micro__services__protobuf_dot_control__center_dot_control__center__models__pb2


class ImportantInfoServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ForceRefreshHomepageInfoCache = channel.unary_unary(
                '/control_center.ImportantInfoService/ForceRefreshHomepageInfoCache',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=micro__services__protobuf_dot_control__center_dot_control__center__models__pb2.HomepageResponse.FromString,
                )
        self.GetHomepageInfos = channel.unary_unary(
                '/control_center.ImportantInfoService/GetHomepageInfos',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=micro__services__protobuf_dot_control__center_dot_control__center__models__pb2.HomepageResponse.FromString,
                )


class ImportantInfoServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ForceRefreshHomepageInfoCache(self, request, context):
        """强制刷新首页信息缓存
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHomepageInfos(self, request, context):
        """获取首页信息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImportantInfoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ForceRefreshHomepageInfoCache': grpc.unary_unary_rpc_method_handler(
                    servicer.ForceRefreshHomepageInfoCache,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=micro__services__protobuf_dot_control__center_dot_control__center__models__pb2.HomepageResponse.SerializeToString,
            ),
            'GetHomepageInfos': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHomepageInfos,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=micro__services__protobuf_dot_control__center_dot_control__center__models__pb2.HomepageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'control_center.ImportantInfoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ImportantInfoService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ForceRefreshHomepageInfoCache(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/control_center.ImportantInfoService/ForceRefreshHomepageInfoCache',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            micro__services__protobuf_dot_control__center_dot_control__center__models__pb2.HomepageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetHomepageInfos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/control_center.ImportantInfoService/GetHomepageInfos',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            micro__services__protobuf_dot_control__center_dot_control__center__models__pb2.HomepageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
